@extends('Layout.app')
@section('content')
    @include('components.banner')
    @include('components.about')
    @include('components.shop')
    @include('components.vegetable')
    @include('components.testmoniam')
    @include('components.contact')
@endsection