@extends('layout.app')
@section('content')
    @include('components.hero')
    @include('components.blog')
    @include('components.newarival')
    @include('components.products')
    @include('components.subscriber')
    @include('components.testmoniam')
@endsection